
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'pqr-lakehouse-dev'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Dask Scheduler (MÃ©tricas de Tareas)
  - job_name: 'dask-scheduler'
    scrape_interval: 10s
    static_configs:
      - targets: ['dask-scheduler:8787']